apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: Never

          livenessProbe:
            exec:
              command: ["cat", "/tmp/healthy"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

          readinessProbe:
            exec:
              command: ["cat", "/tmp/healthy"]
            initialDelaySeconds: 5
            periodSeconds: 5
